# .scrutinizer.yml
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=/tmp/coverage.xml'
                coverage:
                    file: '/tmp/coverage.xml'
                    format: 'clover'
checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*
    paths:
        - src/*