# .scrutinizer.yml
build:
    environment:
        php:
            version: 7.0
    test:
        override:
            -
checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*
    paths:
        - src/*