# .scrutinizer.yml
build:
    environment:
        php:
            version: 7.0.20
                            
checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*
    paths:
        - src/*
