language: php
sudo: true
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs
script:
  - ./scripts/travis.sh
matrix:
  include:
    - php: 5.4
      env: PHPUNIT=false
    - php: 5.5
      env: PHPUNIT=false
    - php: 5.6
      env: PHPUNIT=false
    - php: 7.0
      env: PHPUNIT=true
    - php: 7.1
      env: PHPUNIT=true
    - php: 7.2
      env: PHPUNIT=true
